export const APP_USER_KEY_LOCAL_STORAGE = 'appUserLogin'
export const LOGIN_URL = '/api/login'
export const LOGOUT_URL = '/api/logout'
export const WHO_AM_I_URL = '/api/whoami'
export const AUTHENTICATE_PWD_URL = '/api/user/authenticatepassword'
